apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-serviceaccount
  namespace: ingress-space
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
secrets:
- name: nginx-ingress-serviceaccount-secret-token
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ingress-serviceaccount-secret-token
  namespace: ingress-space
  annotations:
    kubernetes.io/service-account.name: nginx-ingress-serviceaccount
type: kubernetes.io/service-account-token